name: Deploy Level42 Dev Backend

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.DEV_EC2_SSH_KEY }}

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.DEV_EC2_HOST }}
        USERNAME: ${{ secrets.DEV_EC2_USERNAME }}
        DEPLOY_COMMAND: ${{ secrets.DEPLOY_COMMAND }}
      run: ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "${DEPLOY_COMMAND}"
